# Our YAML file for running Travis CI.
language: python
python:
    - "3.6"

services:
    - docker

install:
    - pip install -r docker/requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/gcallah/indras_net

jobs:
    include:
        -stage: test
         name: "Run unit tests"
         script: nosetests indra2/tests/test_*.py
        -stage: deploy
         name: "Deploy to DockerHub"
         script: make container

notifications:
    slack: indras-net:QlnWeHMOpmEHCGJfG3SndDTr
