language: python
python:
    - "3.5"
    - "3.6"
# command to install dependencies:
install:
    - pip install -r requirements-dev.txt
# command to run build (perhaps just tests):
script:
    - nosetests indra2/tests/test_*.py
