language: python
python:
    - "3.6"
# command to install dependencies:
install:
    - pip install -r requirements-dev.txt
# command to run build (perhaps just tests):
env:
    - PYTHONPATH=/home/travis/build/gcallah/indras_net
script:
    - nosetests indra2/tests/test_*.py
