# Our YAML file for running Travis CI.
language: python
python:
    - "3.6"

services:
    - docker

install:
    - pip install -r docker/requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/gcallah/indras_net

script:
    - make pytests
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make prod_container
    - make deploy_container

notifications:
    slack: indras-net:QlnWeHMOpmEHCGJfG3SndDTr
